--- 
- hosts: 172.31.11.146 
  become: yes
  tasks: 
  - name: execute linux command
    command: hostname -f  
    register: myfirsttaskresult

  - name: i want to see first task result 
    debug: 
       msg: "{{myfirsttaskresult}}"  