---
- hosts:  172.31.11.146
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: i want to copy file from ansible master to nodes
    copy: 
       src:  mystaticfile
       dest: /home/ubuntu/mystaticfile

  - name: i wnat to install web server
    apt: 
      name: apache2
      state: present 
      