--- 
- hosts: mywebservers 
  become: yes
  tasks: 
  - name: install java on node ubuntu
    apt: 
      name: "{{myjavapackonubuntu}}"
      state: present 
    when: ansible_os_family =="Debian"   

  - name: install java on Redhat node side 
    yum:  
      name: "{{myjavapackonRedHat}}"
      state: present  
    when: ansible_os_family =="RedHat" 
