--- 
- hosts: 172.31.11.146 
  become: yes 
  tasks:
  - name: install git 
    apt: 
     name: git 
     state: present

  - name: install tree 
    apt: 
     name: tree 
     state: present 

  - name: istall wget
    apt: 
     name: wget 
     state: present 
