--- 
- hosts: 172.31.11.146 
  become: yes 
  tasks:
  - name: install git 
    apt: 
     name: git 
     state: present
    tags: mygit-install 

  - name: install tree 
    apt: 
     name: tree 
     state: present 
    tags: mytree-install
  - name: istall wget
    apt: 
     name: wget 
     state: present 
    tags: mywget-install