---
- hosts: all
  become: yes 
  gather_facts: yes 
  tasks: 
  - name:  i want to install webserver on Ansible node side
    apt:
      name: "{{mywebseverUbuntu}}"
      state: present 
    when: ansible_os_family=="Debian"  

  - name: i want to start the webserver 
    service: 
       name: "{{mywebseverUbuntu}}" 
       state: started     
    when: ansible_os_family=="Debian"

  - name: i want to install webserver 
    yum: 
       name: "{{mywebserverRedhate}}" 
       state: present 
    when: ansible_os_family=="Redhat"

  - name: i want to start Redhat 
    service: 
      name: "{{mywebserverRedhate}}"
      state: started 
    when: ansible_os_family=="Redhat"        
   




