---
- hosts: all
  become: yes 
  gather_facts: yes 
  tasks: 
  - name:  i want to install webserver on Ansible node side
    apt:
      name: apache2
      state: present 
    when: ansible_os_family=="Debian"  

  - name: i want to start the webserver 
    service: 
       name: apache2 
       state: started     
    when: ansible_os_family=="Debian"




